[cargo]
buildScripts.enable = true
features = "all"

[cargo.extraEnv]
CARGO_TARGET_DIR = "target/rust-analyzer"

[files]
exclude_dirs = [
    "target",
    "node_modules",
    "typeshed",
    "logs",
]

[check]
command = "check"
