[package]
name = "beacon-parser"
version = "0.5.0"
edition = "2024"

[dependencies]
tree-sitter.workspace = true
tree-sitter-python.workspace = true
thiserror = "2.0"
owo-colors = "4.2"
rustc-hash = "2.0"
beacon-core = { path = "../core" }
html2md = "0.2.15"
