[book]
authors = ["Owais J"]
language = "en"
multilingual = false
src = "src"
title = "Beacon.rs"

[output.html]
mathjax-support = true
default-theme = "dark"
preferred-dark-theme = "navy"
theme = "theme"
git-repository-url = "https://github.com/stormlightlabs/beacon"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
